### ISSUE TITLE
Use LUISbot to extract entities and intents

### ISSUE THREAD

**Issue by amartyaamp** [amartyaamp/NestorBot#1]
The idea is to have LUISBot return the entities and intents -

Set of tasks that needs to be taken care-
- [ ]  Connecting and authenticating to LUISBOT API in a secure way
- [ ]  Should minimally implement following API - **_def  getTokens (msg)_** ---- returns dictionary of (entities, entity type) pairs, intents

**Comment by amartyaamp** [comment]
Ideally we should encapsulate this in a class  (say LuisBotConnector) which connects the API when an object is created and implements the behaviour in getTokens() .

**Comment by amartyaamp** [comment]
A minimal return string can be something like this - { 'entities' : [(entity, entity_type) , (entity2, entity_type2), ........ ] , 'intents' : [ intent1, intent2] } . This will be for every string sent to LUISBot.

**Comment by sreeragkiyyath** [comment]
Initial commit has been done;
Using luis bot extract intent and entities from query

**Comment by amartyaamp** [comment]
Closing this with #7 .

**Comment by amartyaamp** [comment]
Closing this with #7
